services:
  flux-eco-learnplaces-frontend:
    image: fluxms/flux-eco-learnplaces-frontend:(...)
    environment:
      - FLUX_ECO_LEARNPLACES_FRONTEND_ENDPOINTS_HTTP_PROTOCOL=http
      - FLUX_ECO_LEARNPLACES_FRONTEND_ENDPOINTS_HTTP_HOST=localhost
      - FLUX_ECO_LEARNPLACES_FRONTEND_ENDPOINTS_HTTP_PORT=3100
      - FLUX_ECO_LEARNPLACES_BACKEND_ENDPOINTS_HTTP_PROTOCOL=http
      - FLUX_ECO_LEARNPLACES_BACKEND_ENDPOINTS_HTTP_HOST=localhost
      - FLUX_ECO_LEARNPLACES_BACKEND_ENDPOINTS_HTTP_PORT=3000
    ports:
      - (...):3100:3100